spring:
  sms:
    api-key: ${SMS_API_KEY}
    api-secret: ${SMS_API_SECRET}
    provider: https://api.coolsms.co.kr
    sender: ${SMS_SENDER}
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none # 필요 시 create으로 변경 (컬럼 타입명 변경 등)
    show-sql: true
  cors:
    allowed-origins: ${CORS_ORIGIN}

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true

jwt:
  secret:
    access:
      key: dGhpcyBpcyBhIHZlcnkgbG9uZyBzdHJpbmcgdGhhdCBpcyB1c3VhbGx5IGV4cG9uZW50aWFsIGF1dGhvcml6ZWQgdGhpcyBzdHJpbmc=
    refresh:
      key: Z2V0dGluZyB0aGUgc2VjcmV0IGtleSBmb3IgcmVmcmVzaC10b2tlbiBnb29kIGJvcm5nIGFuZCBzYWZlIG9ubHkgcmFuZG9tIGV4YW1wbGU=
  access:
    token:
      expiration: 1800000  # 30분
  refresh:
    token:
      expiration: 604800000  # 7일
