name: CI/CD Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test tags'
permissions:
  contents: read

jobs:
  docker-build:
    name: Create Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3

      # docker hub 로그인
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Build and Push Docker Image
        run: |
            ./gradlew bootBuildImage --imageName=${{secrets.APP_NAME}}:${{github.sha}}
            docker push ${{secrets.APP_NAME}}:${{github.sha}}
            
      - name: Grant x to gradlew
        run: chmod +x gradlew
        working-directory: ./DutchiePay
        
      - name: Deploy to ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_SSH_PRIVATE_KEY}}
          port: ${{secrets.EC2_PORT}}
          script: |
            docker stop ${{secrets.APP_NAME}}
            docker rm ${{secrets.APP_NAME}}
            
            docker rmi ${{secrets.DOCKER_USER}}/${{secrets.APP_NAME}}:latest
            
            docker pull ${{secrets.DOCKER_USER}}/${{secrets.APP_NAME}}:${{github.sha}}
            
            docker run -d --name ${{secrets.APP_NAME}} -p 8080:8080 \
            --env-file=./.env --network server -v /etc/localtime:/etc/localtime:ro -e TZ=Asia/Seoul --memory="1g" --memory-swap="1g" \
            ${{secrets.DOCKER_USER}}/${{secrets.APP_NAME}}:${{github.sha}}
